### ISSUE TITLE
Unable to write only csv in package to calculate fingerprints

### ISSUE THREAD

**Issue by cescgina** [danielSoler93/drug_learning#17]
Default value for the --parquet option is true, but I found no way to turn it off since the action in the argparse is store_true. I think the default should be False. Then, if the user has not specified any output format either raise an error or set parquet as the output format.

**Comment by danielSoler93** [comment]
Should be resolved in commit 3feaae4cd5e8156fbfaa3f5830a297235b95dd0b

- [X] Custom error if no format is specified
- [X] Parquet default = False

Reopen the issue if does not work
