### ISSUE TITLE
Cannot parallelize mordred descriptors + remove progress bar

### ISSUE THREAD

**Issue by cescgina** [danielSoler93/drug_learning#19]
The calculation of mordred descriptors is internally parallelized via a multiprocessing pool, which crashes if called via a script using another pool. To avoid this issue you can set nproc=1 in the call to calc.pandas in fingerprints.py. I don't know however if it is faster to use a external pool or serially process the file and use the mordred internal pool.

Also you can use quiet=False in the calc.pandas function to avoid the progress bar in the output, which will look bad if the output is redirected to a file.

- [x] Check whether is faster to use mordred pool or and external one
- [x] Fix paralelization of mordred
- [x] Use quiet=False to remove progress bar

**Comment by danielSoler93** [comment]
## Benchmark

External parallelization: 

- 15 sdf files of 1000 in 4 minutes = **4min --> 15K**

Internal parallelization:

- 2,5K in 1min =  **4min --> 10K**

## Solution

External parallelization applied by adding nproc=1
quiet=True set

Reopen if anything else
