### ISSUE TITLE
Docs '' in fingerprint conversion

### ISSUE THREAD

**Issue by danielSoler93** [danielSoler93/drug_learning#22]
When running ``python drug_learning/drug_learning/two_dimensions/main_fingerprints.py test_zinc/*.sdf-mo -pq  split -ch 1000 -nsp 15``it fails with error:

main_fingerprints.py: error: argument split: invalid choice: 'test_zinc/core_1.sdf' (choose from 'split')

If you do ``python drug_learning/drug_learning/two_dimensions/main_fingerprints.py 'test_zinc/*.sdf'-mo -pq  split -ch 1000 -nsp 15`` it works.

Please add that to the docs

**Comment by anasf97** [comment]
Fixed in https://github.com/danielSoler93/drug_learning/commit/d87e7ec9ff743878f6e9d8979867a1575fc8ee26
