### ISSUE TITLE
Parsers different Files

### ISSUE THREAD

**Issue by danielSoler93** [danielSoler93/drug_learning#23]
As the architecture allows to run split and fingerprints separately, and in a future we plan to have many more things we could already split the different argparse in different files and join all of them in the main file.

Tasks: 

- [x] generate splite_argparse.py
- [x] fingerprint_argpares.py
- [x] main.py

**Comment by anasf97** [comment]
Fixed in commit https://github.com/danielSoler93/drug_learning/commit/f8f722583351019dca274094fcbf7b81191822f3

Reopen if it doesn't work.
