### ISSUE TITLE
Parallelize with ray

### ISSUE THREAD

**Issue by danielSoler93** [danielSoler93/drug_learning#24]
Multiprocessing does not share memory between nodes. @cescgina, proposed Ray as a high level library to implement MPI processes to use several nodes at full capacity. First benchmark was 10M  in 14h. (Mordred descriptors).

- [x] Implement Ray for mordred
- [x] Change multiprocessing for ray

**Comment by anasf97** [comment]
Fixed in https://github.com/danielSoler93/drug_learning/commit/958bc74b6f320450f18a26130e68d558dc85127a

Reopen if it doesn't work.
